"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "xxxxxxxx"
email = "xxxxxxxxxxxxxxxxxxx"

[signing]
behavior = "drop"
backend = "gpg"
key = "xxxxxxxxxxxxxxxxxxxx"

[ui]
bookmark-list-sort-keys = ["committer-date", "name"]
# Use Difftastic by default
diff-formatter = ["difft", "--color=always", "$left", "$right"]
# Disable all pagination for commands that support it
paginate = "never"
# Use `meld` as diff editor
diff-editor = "meld"
# Use helix as editor
editor = "hx"
# Use `meld` as merge editor
merge-editor = [
  "meld",
  "$left",
  "$base",
  "$right",
  "-o",
  "$output",
  "--auto-merge",
]

[revset-aliases]
"immutable_heads()" = "builtin_immutable_heads() | (trunk().. & ~mine())"

[git]
fetch = "upstream"
push = "upstream"
track-default-bookmark-on-clone = false
private-commits = "description(glob:'private:*')"
sign-on-push = true

[remote.origin]
auto-track-bookmarks = "glob:*"

[remote.upstream]
auto-track-bookmarks = "main"

[snapshot]
auto-update-stale = true

[templates]
git_push_bookmark = '"push-" ++ change_id.short()'
